### ISSUE TITLE
[Question] How does the XMPP log in?

### ISSUE THREAD

**Issue by imim332** [RobertoGraham/fortnite-2-xmpp#1]
Hi there, 

This library is quite interesting.. But it leaves me to wonder what the XMPP adress is it logs in with, and the password, and the host. As far as I can see from the XMPP logs the host is something with prod.ol.epicgames.com? Please elaborate. Thanks.

**Comment by RobertoGraham** [comment]
XMPP Domain: `prod.ol.epicgames.com`
Host: `xmpp-service-prod.ol.epicgames.com`
Port: `5222`
Username: ID of the Epic account
Password: Access token obtained from the Token instance returned by this method: https://github.com/RobertoGraham/fortnite-2/blob/master/src/main/java/io/github/robertograham/fortnite2/client/Fortnite.java#L50
User JID: `accountId@prod.ol.epicgames.com`

Any good Fortnite client will expose details of their authentication sessions from which you can get the access token needed
